const langObj = {
  'en': {
    'name': 'Ivan Kasenka',
    'contacts': 'Contacts',
    'about-myself': 'About myself',
    'education': 'Education',
    'languages': 'Languages',
    'skills': 'Skills',
    'work-experience': 'Work Experience',
    'portfolio': 'Portfolio',
    'about': "I'm 28 years old and I come from Belarus, city of Brest. Nowadays I continue to develop my technical skills. I think ability to learn is one of my strongest features. As a perfectionist I am trying to complete my projects correctly and strictly. Also I am a quick learner and a team worker who gets the job done.",
    'language-1': 'Russian - Native',
    'language-2': 'English - Intermediate',
    'skill-1': 'Сonfident knowledge of HTML5, CSS3, JavaScript(ES6+), Git, GitHub;',
    'skill-1.1': 'Experience of layout of layouts from Figma;',
    'skill-2': 'Able to work with with Webpack, npm, eslint;',
    'skill-3': 'Experience in cross-browser&adaptive website coding;',
    'skill-4': 'Adherence to the principles of SOLID, DRY, KISS, YAGNI;',
    'skill-4.1': 'Naming according to BEM;',
    'skill-5': 'Understanding the basics of OOP;',
    'skill-6': 'Basic knowledge of the React library, AntD UI framework;',
    'skill-7': 'Web site development experience using Visual Studio Code;',
    'skill-8': 'Worked with the JIRA, ManageEngine ServiceDesk project management systems.',
    'education-1-title': 'Bachelor of Computer Science',
    'education-1-subtitle': 'from Brest State Technical University',
    'education-1-time': '2015 - 2020',
    'education-1-li-1': 'Speciality: artificial intelligence;',
    'education-1-li-2': 'Qualification: system engineer;',
    'education-1-li-3': 'Diploma project: Development of a lane control module for an autopilot.',
    'work-1-title': 'Database administrator',
    'work-1-subtitle': 'at Inspectorate of the Ministry of Taxes and Duties',
    'work-1-time': 'August, 2020 - August, 2023',
    'work-1-li-1': 'Accompanied the internal software;',
    'work-1-li-2': 'Monitored database health;',
    'work-1-li-3': 'Worked with developers on issues of interaction, testing and implementation of software;',
    'work-1-li-4': 'Worked with databases using SQL queries;',
    'work-1-li-5': 'Processed program errors and provided them to software developers;',
    'work-1-li-6': 'Accompanied work places.',
    'work-2-title': 'System Administrator',
    'work-2-subtitle': 'at Ernis LLC',
    'work-2-time': 'September, 2024 - March, 2026',
    'work-2-li-1': "Maintained and upgraded PCs, troubleshooted Windows and Linux OS, and software;",
    'work-2-li-2': 'Supported and developed network infrastructure, configured and supported network equipment and services;',
    'work-2-li-3': 'Configured and maintained office equipment (MFPs, printers, scanners), organized repairs if necessary;',
    'work-2-li-4': 'Experience with video surveillance and access control systems;',
    'work-2-li-5': 'Experience with various devices, such as TSD, scanners, price checkers, IP phones, cameras;',
    'work-2-li-6': "Maintaining documentation and reporting of the company's IT infrastructure assets.",
    'work-2-li-7': 'Experience with cryptographic software Avest for setting up work with web resources of banks and government agencies;',
    'work-2-li-8': 'User technical support;',
    'work-2-li-9': 'Ensuring uninterrupted communication between structural divisions;',
    'work-2-li-10': "Maintaining documentation and reporting of the company's IT infrastructure assets.",
    'project-1__title': 'Shelter',
    'project-1__description': 'Landing page',
    'project-2__title': 'Minesweeper',
    'project-2__description': 'Small app for fun.',
    'project-3__title': 'Virtual keyboard',
    'project-3__description': 'Small app for fun.',
    'code': 'Code'
  },
  'ru': {
    'name': 'Иван Косенко',
    'contacts': 'Контакты',
    'about-myself': 'Обо мне',
    'education': 'Образование',
    'languages': 'Языки',
    'skills': 'Навыки',
    'work-experience': 'Опыт работы',
    'portfolio': 'Портфолио',
    'about': 'Мне 28 лет и я родом из Беларуси , города Бреста. С каждым днем я продолжаю усовершенствовать свои технические навыки. По моему мнению способность обучаться и легко усваивать полученную информацию - одна из моих сильных качеств. Будучи перфекционистом я прикладываю все усилия для того, чтобы моя работа была выполнена качественно и точно. Также я способен быстро обучаться и работать в команде.',
    'language-1': 'Русский - Родной',
    'language-2': 'Английский - Продвинутый уровень',
    'skill-1': 'Уверенные знания HTML5, CSS3, JavaScript(ES6+), Git, GitHub;',
    'skill-1.1': 'Опыт верстки макетов из Figma;',
    'skill-2': 'Работал с Webpack, npm, eslint;',
    'skill-3': 'Опыт кроссбраузерной и адаптивной верстки сайтов;',
    'skill-4': 'Соблюдение принципов SOLID, DRY, KISS, YAGNI;',
    'skill-4.1': 'Именование по БЭМу;',
    'skill-5': 'Понимание основ ООП;',
    'skill-6': 'Базовые знания библиотеки React, UI фреймворк AntD;',
    'skill-7': 'Опыт разработки веб-сайтов с использованием Visual Studio Code;',
    'skill-8': 'Работал с системами управления проектами JIRA, ManageEngine ServiceDesk.',
    'education-1-title': 'Бакалавр компьютерных наук',
    'education-1-subtitle': 'Брестского государственного технического университета',
    'education-1-time': '2015 - 2020',
    'education-1-li-1': 'Специальность: искусственный интеллект;',
    'education-1-li-2': 'Квалификация: инженер - системотехник;',
    'education-1-li-3': 'Дипломный проект: Разработка модуля контроля движения по полосе для автопилота.',
    'work-1-title': 'Администратор баз данных',
    'work-1-subtitle': 'в инспекции Министерства по налогам и сборам',
    'work-1-time': 'Август, 2020 - Август, 2023',
    'work-1-li-1': 'Сопровождал внутреннее программное обеспечение;',
    'work-1-li-2': 'Мониторил работоспособность базы данных;',
    'work-1-li-3': 'Работал с разработчиками по вопросам взаимодействия, тестирования и внедрения ПО;',
    'work-1-li-4': 'Работал с базами данных посредством SQL запросов;',
    'work-1-li-5': 'Обрабатывал ошибки программ и предоставлял их разработчикам ПО;',
    'work-1-li-6': 'Сопровождал рабочие места.',
    'work-2-title': 'Системный администратор',
    'work-2-subtitle': 'в ООО "Эрнис"',
    'work-2-time': 'Сентябрь, 2024 - Март, 2026',
    'work-2-li-1': 'Обслуживание и модернизирование ПК, устранение неисправностей ОС Windows и Linux, и ПО;',
    'work-2-li-2': 'Поддержка и развитие сетевой инфраструктуры, настройка и сопровождение сетевого оборудования и сервисов;',
    'work-2-li-3': 'Настройка и обслуживание офисной техники (МФУ, принтеры, сканеры), при необходимости организация ремонта;',
    'work-2-li-4': 'Опыт работы с системой видеонаблюдения(Trassir) и СКУД;',
    'work-2-li-5': 'Опыт работы с различными устройствами, такие как ТСД, сканеры, прайсчекеры, IP телефоны(grandstream, yealink), камеры;',
    'work-2-li-6': 'Опыт работы с кассовым оборудованием на базе ПО Artix, настройка и устранение сетевых ошибок;',
    'work-2-li-7': 'Опыт работы с криптографическим ПО Авест для настройки работы с веб-ресурсами банков и государственных органов;',
    'work-2-li-8': 'Техническая поддержка пользователей;',
    'work-2-li-9': 'Обеспечение бесперебойной связи между структурными подразделениями;',
    'work-2-li-10': 'Ведение документации и отчётности активов IT инфраструктуры компании.',
    'project-1__title': 'Приют для животных',
    'project-1__description': 'Лендинг',
    'project-2__title': 'Сапёр',
    'project-2__description': 'Небольшое приложение забавы ради',
    'project-3__title': 'Виртуальная клавиатура',
    'project-3__description': 'Небольшое приложение забавы ради',
    'code': 'Код',
  }
}
export default langObj;